import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:exam_paper/app.dart';
import 'package:exam_paper/firebase_options.dart'; // Ensure this is generated by flutterfire configure
import 'package:exam_paper/notification_service.dart'; // Corrected import path

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Using the top-level function for background messages
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Initialize providers before runApp to ensure services are ready
  final container = ProviderContainer();
  try {
    await container.read(notificationServiceProvider).initialize();
  } catch (e) {
    debugPrint('Failed to initialize notification service: $e');
  }

  runApp(
    // UncontrolledProviderScope is used when we manage the ProviderContainer manually
    UncontrolledProviderScope(container: container, child: const ExamApp()),
  );
}
